# project informations for Bukkit in order to register our plugin with all it components
# ${project.name} are variables from Maven (pom.xml) which will be replaced after the build
name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}

# meta informations for plugin managers
authors: [games647, 'https://github.com/games647/ScoreboardStats/graphs/contributors']
description: |
    ${project.description}
website: ${project.url}
dev-url: ${project.url}

# depending on them - load after them to make sure they are initialized
softdepend:
    - ProtocolLib
    - InSigns
    # Variable dependencies
    - PlaceholderAPI
    - mcMMO
    - Vault
    - SimpleClans
    - Factions
    - Heroes
    - uSkyBlock
    - PlayerPoints
    - Craftconomy3
    - ASkyBlock

# Root commands to register automatically to Bukkit
commands:
  # choose a unique name in order to register it successfully
  ${project.artifactId}:
    description: 'Root command for all commands in ${project.name}'
    aliases: [side, ss, sb, board, sidebar]

# Permission managment
permissions:
  ${project.artifactId}.admin:
    children:
      ${project.artifactId}.reload: true
      ${project.artifactId}.sign: true
      ${project.artifactId}.use: true
      ${project.artifactId}.hide: true
  ${project.artifactId}.member:
    default: true
    children:
      ${project.artifactId}.use: true
      ${project.artifactId}.hide: true
  ${project.artifactId}.use:
    description: 'Sender is allowed to see the scoreboard'
  ${project.artifactId}.sign:
    description: 'Sender can make signs with variables on it'
  ${project.artifactId}.reload:
    description: 'Sender can perform a plugin reload'
  ${project.artifactId}.hide:
    description: 'Sender can toggle the scoreboard'
