name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}

# meta informations for plugin managers
author: [games647, 'https://github.com/games647/ScoreboardStats/graphs/contributors']
description: |
    ${project.description}
website: ${project.url}
dev-url: ${project.url}

# depending on them
softdepend:
    - ProtocolLib
    - mcMMO
    - Vault
    - SimpleClans
    - InSigns
    - Factions
    - Heroes
    - uSkyBlock
    - PlayerPoints

commands:
  sidebar:
    description: 'Root command for all commands in ScoreboardStats'
    aliases: [scoreboardstats, side, ss, sb, board]

permissions:
  scoreboardstats.admin:
    children:
      scoreboardstats.reload: true
      scoreboardstats.sign: true
      scoreboardstats.use: true
      scoreboardstats.hide: true
  scoreboardstats.member:
    default: true
    children:
      scoreboardstats.use: true
      scoreboardstats.hide: true
  scoreboardstats.use:
    description: 'Sender is allowed to see the scoreboard'
  scoreboardstats.sign:
    description: 'Sender can make signs with variables on it'
  scoreboardstats.reload:
    description: 'Sender can perform a plugin reload'
  scoreboardstats.hide:
    description: 'Sender can toggle the scoreboard'
